### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by mrakitin**
Based on the #4 PR branch commits.

#4 should be merged first. Then here, we can rebase on `main`.

### CODE REVIEW

**Comment by mrakitin** [comment]
Not sure why https://travis-ci.com/github/NSLS-II/pizza-box/jobs/397625484 fails, but https://travis-ci.com/github/bluesky/bluesky-queueserver/jobs/397618867 (from a different project, but with a very similar configuration) passes. Any ideas, @jklynch?

**Comment by lcdesilva** [comment]
Guys, I looked through the changes. I have no comments to make. @jklynch, do you have feedback?

**Comment by mrakitin** [comment]
Surprisingly, it worked for `bluesky-queueserver` where we also switched to main.

**Comment by jklynch** [comment]
I added a gh-pages branch.

**Comment by mrakitin** [comment]
Interesting, how did it help? :)

**Comment by jklynch** [comment]
I don't know. But that was the first difference I saw between this PR and the bluesky-queueserver PR you mentioned. Maybe this is a bug in doctr? "git checkout master" is hardcoded there in at least one place.

**Comment by mrakitin** [comment]
Nice catch, thanks @jklynch!

I guess it's somehow related to the presense of the `gh-pages` branch, which did not exist here. In the case of the queueserver, the documentation was pushed when the base branch was still called `master`, and then it got renamed to `main`, so `doctr` did not fail. At least we know a workaround now.

**Pull request merged**
